/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Call */

#ifndef _Included_Call
#define _Included_Call
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Call
 * Method:    Heapsort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Call_Heapsort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
